steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest', '.']
  
  # 2. Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest']
  
  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Ensure public access is maintained if that was the intent, consistent with typical web apps.

substitutions:
    # These values are read from deploy.config or can be overridden in Cloud Build Trigger
    # To update: Edit deploy.config file
    _SERVICE_NAME: data-qa-agent-frontend
    _REGION: us-central1
    _PROJECT_ID: leyin-sandpit

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'

options:
  logging: CLOUD_LOGGING_ONLY

